# Generated by Django 2.1.2 on 2018-10-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_unit', models.CharField(blank=True, choices=[('SqFt', 'SqFt')], max_length=50, null=True)),
                ('bathrooms', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
