# Generated by Django 2.1.2 on 2018-10-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='housedata',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housedata',
            name='bedrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housedata',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housedata',
            name='home_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housedata',
            name='home_type',
            field=models.CharField(blank=True, choices=[('Single Family', 'SingleFamily')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='housedata',
            name='last_sold_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housedata',
            name='last_sold_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housedata',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housedata',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housedata',
            name='property_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housedata',
            name='rent_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housedata',
            name='rentzestimate_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housedata',
            name='rentzestimate_last_updated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housedata',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='housedata',
            name='tax_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housedata',
            name='tax_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housedata',
            name='year_built',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housedata',
            name='zestimate_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housedata',
            name='zestimate_last_updated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housedata',
            name='zillow_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='housedata',
            name='zipcode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
